from sqlalchemy import create_engine, Column, Integer, Float, String, Date
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Define the SQLAlchemy engine
SQLALCHEMY_DATABASE_URL = "sqlite:///./properties.db"
engine = create_engine(SQLALCHEMY_DATABASE_URL)

# Define the Base class for declarative ORM
Base = declarative_base()

# Define the model class
class Property(Base):
    __tablename__ = "properties"

    id = Column(Integer, primary_key=True, index=True)
    full_address = Column(String)
    longitude = Column(Float)
    latitude = Column(Float)
    zip_code = Column(String)
    rec_type = Column(String)
    pin = Column(String)
    ovaclass = Column(Integer)
    class_description = Column(String)
    current_land = Column(Float)
    current_building = Column(Float)
    current_total = Column(Float)
    estimated_market_value = Column(Float)
    prior_land = Column(Float)
    prior_building = Column(Float)
    prior_total = Column(Float)
    pprior_land = Column(Float)
    pprior_building = Column(Float)
    pprior_total = Column(Float)
    pprior_year = Column(Integer)
    town = Column(Integer)
    volume = Column(Integer)
    loc = Column(String)
    tax_code = Column(Integer)
    neighborhood = Column(Integer)
    houseno = Column(Integer)
    direction = Column(String)
    street = Column(String)
    suffix = Column(String)
    apt = Column(String)
    city = Column(String)
    res_type = Column(String)
    bldg_use = Column(String)
    apt_desc = Column(String)
    comm_units = Column(Integer)
    ext_desc = Column(String)
    full_bath = Column(Integer)
    half_bath = Column(Integer)
    bsmt_desc = Column(String)
    attic_desc = Column(String)
    ac = Column(String)
    fireplace = Column(String)
    gar_desc = Column(String)
    age = Column(Integer)
    building_sq_ft = Column(Integer)
    land_sq_ft = Column(Integer)
    bldg_sf = Column(Integer)
    units_tot = Column(Integer)
    multi_sale = Column(String)
    deed_type = Column(String)
    sale_date = Column(String)
    sale_amount = Column(Float)
    appcnt = Column(Integer)
    appeal_a = Column(String)
    appeal_a_status = Column(String)
    appeal_a_result = Column(String)
    appeal_a_reason = Column(String)
    appeal_a_pin_result = Column(String)
    appeal_a_propav = Column(String)
    appeal_a_currav = Column(String)
    appeal_a_resltdate = Column(String)

# Create the database tables
Base.metadata.create_all(bind=engine)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
